In [1]:
!pip install mediapipe opencv-python

In [2]:
import cv2
import mediapipe as mp
import numpy as np
mp_drawing = mp.solutions.drawing_utils
mp_pose = mp.solutions.pose
import pandas as pd
from PIL import ImageFont, ImageDraw, Image
from tensorflow.keras.models import load_model

In [3]:
def calculate_angle(a,b,c):
    a = np.array(a) # First
    b = np.array(b) # Mid
    c = np.array(c) # End
    
    radians = np.arctan2(c[1]-b[1], c[0]-b[0]) - np.arctan2(a[1]-b[1], a[0]-b[0])
    angle = np.abs(radians*180.0/np.pi)
    
    if angle >180.0:
        angle = 360-angle
        
    return angle 

In [4]:
Nose_X = []
Nose_y = []
Left_Eye_X = []
Left_Eye_y = []
Right_Eye_X = []
Right_Eye_y = []
Left_Ear_X = []
Left_Ear_y = []
Right_Ear_X = []
Right_Ear_y = []
Left_Shoulder_X = []
Left_Shoulder_y = []
Right_Shoulder_X = []
Right_Shoulder_y = []
Left_Elbow_X = []
Left_Elbow_y = []
Right_Elbow_X = []
Right_Elbow_y = []
Left_Wrist_X = []
Left_Wrist_y = []
Right_Wrist_X = []
Right_Wrist_y = []
Left_Hip_X = []
Left_Hip_y = []
Right_Hip_X = []
Right_Hip_y = []
Left_Knee_X= []
Left_Knee_y= []
Right_Knee_X = []
Right_Knee_y = []
Left_Ankle_X = []
Left_Ankle_y = []
Right_Ankle_X = []
Right_Ankle_y = []
Left_Foot_X = []
Left_Foot_y = []
Right_Foot_X = []
Right_Foot_y = []

In [12]:
from enum import auto
from turtle import width


cap = cv2.VideoCapture(0)

# Curl counter variables
counter = 0 
stage = None

## Setup mediapipe instance
with mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5) as pose:
    while cap.isOpened():
        ret, frame = cap.read()
        
        # Recolor image to RGB
        image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        image.flags.writeable = False
      
        # Make detection
        results = pose.process(image)
    
        # Recolor back to BGR
        image.flags.writeable = True
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
        
        # Extract landmarks
        try:
            landmarks = results.pose_landmarks.landmark
            
            # Get coordinates
            
            shoulder = [landmarks[mp_pose.PoseLandmark.LEFT_SHOULDER.value].x,landmarks[mp_pose.PoseLandmark.LEFT_SHOULDER.value].y]
            elbow = [landmarks[mp_pose.PoseLandmark.LEFT_ELBOW.value].x,landmarks[mp_pose.PoseLandmark.LEFT_ELBOW.value].y]
            wrist = [landmarks[mp_pose.PoseLandmark.LEFT_WRIST.value].x,landmarks[mp_pose.PoseLandmark.LEFT_WRIST.value].y]
          
            # Calculate angle
            angle = calculate_angle(shoulder, elbow, wrist)
         
            
            # Visualize angle
            cv2.putText(image, str(angle), 
                           tuple(np.multiply(elbow, [1920, 1080]).astype(int)),
                           cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2, cv2.LINE_AA
                                )
            
       # Curl counter logic
            if angle  > 160:
                stage = "down"
            if angle< 30 and stage =='down':
                stage="up"
                counter +=1
               
                
            
                                              
            Nose = list(tuple(np.multiply([landmarks[mp_pose.PoseLandmark.NOSE.value].x,landmarks[mp_pose.PoseLandmark.NOSE.value].y], [1920, 1080]).astype(int)))

            Left_Eye = list(tuple(np.multiply([landmarks[mp_pose.PoseLandmark.LEFT_EYE.value].x,landmarks[mp_pose.PoseLandmark.LEFT_EYE.value].y], [1920, 1080]).astype(int)))
            Right_Eye = list(tuple(np.multiply([landmarks[mp_pose.PoseLandmark.RIGHT_EYE.value].x,landmarks[mp_pose.PoseLandmark.RIGHT_EYE.value].y], [1920, 1080]).astype(int)))

            Left_Ear = list(tuple(np.multiply([landmarks[mp_pose.PoseLandmark.LEFT_EAR.value].x,landmarks[mp_pose.PoseLandmark.LEFT_EAR.value].y], [1920, 1080]).astype(int)))
            Right_Ear = list(tuple(np.multiply([landmarks[mp_pose.PoseLandmark.RIGHT_EAR.value].x,landmarks[mp_pose.PoseLandmark.RIGHT_EAR.value].y], [1920, 1080]).astype(int)))

            Left_Shoulder = list(tuple(np.multiply([landmarks[mp_pose.PoseLandmark.LEFT_SHOULDER.value].x,landmarks[mp_pose.PoseLandmark.LEFT_SHOULDER.value].y], [1920, 1080]).astype(int)))
            Right_Shoulder = list(tuple(np.multiply([landmarks[mp_pose.PoseLandmark.RIGHT_EAR.value].x,landmarks[mp_pose.PoseLandmark.RIGHT_EAR.value].y], [1920, 1080]).astype(int)))

            Left_Elbow = list(tuple(np.multiply([landmarks[mp_pose.PoseLandmark.LEFT_ELBOW.value].x,landmarks[mp_pose.PoseLandmark.LEFT_ELBOW.value].y], [1920, 1080]).astype(int)))
            Right_Elbow = list(tuple(np.multiply([landmarks[mp_pose.PoseLandmark.RIGHT_ELBOW.value].x,landmarks[mp_pose.PoseLandmark.RIGHT_ELBOW.value].y], [1920, 1080]).astype(int)))

            Left_Wrist = list(tuple(np.multiply([landmarks[mp_pose.PoseLandmark.LEFT_WRIST.value].x,landmarks[mp_pose.PoseLandmark.LEFT_WRIST.value].y], [1920, 1080]).astype(int)))
            Right_Wrist = list(tuple(np.multiply([landmarks[mp_pose.PoseLandmark.RIGHT_WRIST.value].x,landmarks[mp_pose.PoseLandmark.RIGHT_WRIST.value].y], [1920, 1080]).astype(int)))

            Left_Hip = list(tuple(np.multiply([landmarks[mp_pose.PoseLandmark.LEFT_HIP.value].x,landmarks[mp_pose.PoseLandmark.LEFT_HIP.value].y], [1920, 1080]).astype(int)))
            Right_Hip = list(tuple(np.multiply([landmarks[mp_pose.PoseLandmark.RIGHT_HIP.value].x,landmarks[mp_pose.PoseLandmark.RIGHT_HIP.value].y], [1920, 1080]).astype(int)))

            Left_Knee = list(tuple(np.multiply([landmarks[mp_pose.PoseLandmark.LEFT_KNEE.value].x,landmarks[mp_pose.PoseLandmark.LEFT_KNEE.value].y], [1920, 1080]).astype(int)))
            Right_Knee = list(tuple(np.multiply([landmarks[mp_pose.PoseLandmark.RIGHT_KNEE.value].x,landmarks[mp_pose.PoseLandmark.RIGHT_KNEE.value].y], [1920, 1080]).astype(int)))

            Left_Ankle = list(tuple(np.multiply([landmarks[mp_pose.PoseLandmark.LEFT_ANKLE.value].x,landmarks[mp_pose.PoseLandmark.LEFT_ANKLE.value].y], [1920, 1080]).astype(int)))
            Right_Ankle = list(tuple(np.multiply([landmarks[mp_pose.PoseLandmark.RIGHT_ANKLE.value].x,landmarks[mp_pose.PoseLandmark.RIGHT_ANKLE.value].y], [1920, 1080]).astype(int)))


            Left_Foot = list(tuple(np.multiply([landmarks[mp_pose.PoseLandmark.LEFT_FOOT_INDEX.value].x,landmarks[mp_pose.PoseLandmark.LEFT_FOOT_INDEX.value].y], [1920, 1080]).astype(int)))
            Right_Foot = list(tuple(np.multiply([landmarks[mp_pose.PoseLandmark.RIGHT_FOOT_INDEX.value].x,landmarks[mp_pose.PoseLandmark.RIGHT_FOOT_INDEX.value].y], [1920, 1080]).astype(int)))
            
            Nose_X.append(Nose[0])
            Nose_y.append(Nose[1])
            Left_Eye_X.append(Left_Eye[0])
            Left_Eye_y.append(Left_Eye[1])
            Right_Eye_X.append(Right_Eye[0])
            Right_Eye_y.append(Right_Eye[1])
            Left_Ear_X.append(Left_Ear[0])
            Left_Ear_y.append(Left_Ear[1])
            Right_Ear_X.append(Right_Ear[0])
            Right_Ear_y.append(Right_Ear[1])
            Left_Shoulder_X.append(Left_Shoulder[0])
            Left_Shoulder_y.append(Left_Shoulder[1])
            Right_Shoulder_X.append(Right_Shoulder[0])
            Right_Shoulder_y.append(Right_Shoulder[1])
            Left_Elbow_X.append(Left_Elbow[0])
            Left_Elbow_y.append(Left_Elbow[1])
            Right_Elbow_X.append(Right_Elbow[0])
            Right_Elbow_y.append(Right_Elbow[1])
            Left_Wrist_X.append(Left_Wrist[0])
            Left_Wrist_y.append(Left_Wrist[1])
            Right_Wrist_X.append(Right_Wrist[0])
            Right_Wrist_y.append(Right_Wrist[1])
            Left_Hip_X.append(Left_Hip[0])
            Left_Hip_y.append(Left_Hip[1])
            Right_Hip_X.append(Right_Hip[0])
            Right_Hip_y.append(Right_Hip[1])
            Left_Knee_X.append(Left_Knee[0])
            Left_Knee_y.append(Left_Knee[1])
            Right_Knee_X.append(Right_Knee[0])
            Right_Knee_y.append(Right_Knee[1])
            Left_Ankle_X.append(Left_Ankle[0])
            Left_Ankle_y.append(Left_Ankle[1])
            Right_Ankle_X.append(Right_Ankle[0])
            Right_Ankle_y.append(Right_Ankle[1])
            Left_Foot_X.append(Left_Foot[0])
            Left_Foot_y.append(Left_Foot[1])
            Right_Foot_X.append(Right_Foot[0])
            Right_Foot_y.append(Right_Foot[1])
            
            a = pd.DataFrame({"Nose_X" : Nose_X,
                       "Nose_y" :Nose_y,
                       "Left_Eye_X" :Left_Eye_X,
                       "Left_Eye_y" : Left_Eye_y,
                       "Right_Eye_X" : Right_Eye_X,
                       "Right_Eye_y" : Right_Eye_y,
                       "Left_Ear_X":Left_Ear_X,
                       "Left_Ear_y":Left_Ear_y,
                       "Right_Ear_X":Right_Ear_X,
                       "Right_Ear_y":Right_Ear_y,
                       "Left_Shoulder_X":Left_Shoulder_X,
                       "Left_Shoulder_y" :Left_Shoulder_y,
                       "Right_Shoulder_X":Right_Shoulder_X,
                       "Right_Shoulder_y":Right_Shoulder_y,
                       "Right_Elbow_X":Right_Elbow_X,
                       "Right_Elbow_y":Right_Elbow_y,
                       "Right_Wrist_X":Right_Wrist_X,
                       "Right_Wrist_y":Right_Wrist_y,
                       "Left_Hip_X":Left_Hip_X,
                       "Left_Hip_y":Left_Hip_y,
                       "Right_Hip_X":Right_Hip_X,
                       "Right_Hip_y":Right_Hip_y,
                       "Left_Knee_X":Left_Knee_X,
                       "Left_Knee_y":Left_Knee_y,
                       "Right_Knee_X":Right_Knee_X,
                       "Right_Knee_y":Right_Knee_y,
                       "Left_Ankle_X":Left_Ankle_X,
                       "Left_Ankle_y":Left_Ankle_y,
                       "Right_Ankle_X":Right_Ankle_X,
                       "Right_Ankle_y":Right_Ankle_y,
                       "Left_Foot_X":Left_Foot_X,
                       "Left_Foot_y":Left_Foot_y,
                       "Right_Foot_X":Right_Foot_X,
                       "Right_Foot_y":Right_Foot_y
    
            })
            
            
            
        except:
            pass
        
        # Render curl counter
        # Setup status box
        
       
        cv2.rectangle(image, (0,0), (225,73), (245,117,16), -1)
        
        # Rep data
        cv2.putText(image, 'REPS', (15,12), 
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,0,0), 1, cv2.LINE_AA)
        cv2.putText(image, str(counter), 
                    (10,60), 
                    cv2.FONT_HERSHEY_SIMPLEX, 2, (255,255,255), 2, cv2.LINE_AA)
        
        # Stage data
        cv2.putText(image, 'STAGE', (65,12), 
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,0,0), 1, cv2.LINE_AA)
        cv2.putText(image, stage, 
                    (60,60), 
                    cv2.FONT_HERSHEY_SIMPLEX, 2, (255,255,255), 2, cv2.LINE_AA)
        
        cv2.rectangle(image, (200,150), (400, 450), (50,150,255), 2  )
        font = cv2.FONT_ITALIC
        cv2.putText(image,"sit down here!", (200, 100), font, 1, (0,200,0), 3)
        
        
        # Render detections
        mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_pose.POSE_CONNECTIONS,
                                mp_drawing.DrawingSpec(color=(245,117,66), thickness=2, circle_radius=2), 
                                mp_drawing.DrawingSpec(color=(245,66,230), thickness=2, circle_radius=2) 
                                 )               
        
        cv2.imshow('Mediapipe Feed', image)
        
    
        if cv2.waitKey(10) & 0xFF == ord('q'):
            break 
        elif counter == 5 :

            cv2.waitKey(1000)
            break

    cap.release()
    cv2.destroyAllWindows()


model = load_model('latpulldown.h5') #cnn에서 학습한 파일을 갖고 옴
b = model.predict(a) #모델예측
c = np.argmax(b, axis=1) #운동 자세 판별
print(b)
print(c)




40/40 [==============================] - 0s 690us/step
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
[ 6 13 13 ... 13 13 13]


In [43]:
from enum import auto
from multiprocessing.sharedctypes import Value
from turtle import width

def calculate_angle(a,b,c):
    a = np.array(a) # First
    b = np.array(b) # Mid
    c = np.array(c) # End
    
    radians = np.arctan2(c[1]-b[1], c[0]-b[0]) - np.arctan2(a[1]-b[1], a[0]-b[0])
    angle = np.abs(radians*180.0/np.pi)
    
    if angle >180.0:
        angle = 360-angle
        
    return angle 


from enum import auto
from turtle import width


cap = cv2.VideoCapture(0)

# Curl counter variables
counter = 0 

result = []
stage = 'up'
## Setup mediapipe instance
with mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5) as pose:
    while cap.isOpened():
        ret, frame = cap.read()
        
        # Recolor image to RGB
        image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        image.flags.writeable = False
    
        # Make detection
        results = pose.process(image)
    
        # Recolor back to BGR
        image.flags.writeable = True
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
        
        # Extract landmarks
        try:
            landmarks = results.pose_landmarks.landmark
            
            # Get coordinates
            shoulder = [landmarks[mp_pose.PoseLandmark.LEFT_SHOULDER.value].x,landmarks[mp_pose.PoseLandmark.LEFT_SHOULDER.value].y]
            elbow = [landmarks[mp_pose.PoseLandmark.LEFT_ELBOW.value].x,landmarks[mp_pose.PoseLandmark.LEFT_ELBOW.value].y]
            wrist = [landmarks[mp_pose.PoseLandmark.LEFT_WRIST.value].x,landmarks[mp_pose.PoseLandmark.LEFT_WRIST.value].y]
            
            
            
            shoulder_L = [landmarks[mp_pose.PoseLandmark.LEFT_SHOULDER.value].x,landmarks[mp_pose.PoseLandmark.LEFT_SHOULDER.value].y] # 왼쪽
            shoulder_R = [landmarks[mp_pose.PoseLandmark.RIGHT_SHOULDER.value].x,landmarks[mp_pose.PoseLandmark.RIGHT_SHOULDER.value].y] # 오른쪽
            elbow_L = [landmarks[mp_pose.PoseLandmark.LEFT_ELBOW.value].x,landmarks[mp_pose.PoseLandmark.LEFT_ELBOW.value].y] # 왼쪽
            elbow_R = [landmarks[mp_pose.PoseLandmark.RIGHT_ELBOW.value].x,landmarks[mp_pose.PoseLandmark.RIGHT_ELBOW.value].y] # 오른쪽
            wrist_L = [landmarks[mp_pose.PoseLandmark.LEFT_WRIST.value].x,landmarks[mp_pose.PoseLandmark.LEFT_WRIST.value].y] # 왼쪽
            wrist_R = [landmarks[mp_pose.PoseLandmark.RIGHT_WRIST.value].x,landmarks[mp_pose.PoseLandmark.RIGHT_WRIST.value].y] # 오른쪽
            hip_L = [landmarks[mp_pose.PoseLandmark.LEFT_HIP.value].x,landmarks[mp_pose.PoseLandmark.LEFT_HIP.value].y] # 왼쪽
            hip_R = [landmarks[mp_pose.PoseLandmark.RIGHT_HIP.value].x,landmarks[mp_pose.PoseLandmark.RIGHT_HIP.value].y] # 오른쪽
            
            
            
            
            
            
            # Calculate angle
            angle = calculate_angle(shoulder, elbow, wrist)
            
            # Visualize angle
            cv2.putText(image, str(angle), 
                        tuple(np.multiply(elbow, [1920, 1080]).astype(int)), 
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2, cv2.LINE_AA
                                )
            
            # Curl counter logic
            if stage == 'up' :
                if angle > 160 :
                    stage = "down"
                    s = 1
                    if counter >= 1:
                        twoShape = []
                        oneShape = []
                        for num in ['shoulder_L','shoulder_R','elbow_L','elbow_R','wrist_L','wrist_R','hip_L','hip_R']:
                            oneShape += list(tuple(np.multiply(eval(f'{num}'), [1920, 1080]).astype(int)))
                        twoShape += [oneShape]
                        result += [twoShape]
                            
            if angle < 30 and stage =='down':
                stage="up"
                if s == 1 :
                    if counter == 5 :
                        cv2.waitKey(3000)
                        break
                counter +=1
                
            
                    
        except:
            pass
        
        # Render curl counter
        # Setup status box
        cv2.rectangle(image, (0,0), (225,73), (245,117,16), -1)
        
        # Rep data
        cv2.putText(image, 'REPS', (15,12), 
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,0,0), 1, cv2.LINE_AA)
        cv2.putText(image, str(counter), 
                    (10,60), 
                    cv2.FONT_HERSHEY_SIMPLEX, 2, (255,255,255), 2, cv2.LINE_AA)
        
        # Stage data
        cv2.putText(image, 'STAGE', (65,12), 
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,0,0), 1, cv2.LINE_AA)
        cv2.putText(image, stage, 
                    (60,60), 
                    cv2.FONT_HERSHEY_SIMPLEX, 2, (255,255,255), 2, cv2.LINE_AA)
        
        
        # Render detections
        mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_pose.POSE_CONNECTIONS,
                                mp_drawing.DrawingSpec(color=(245,117,66), thickness=2, circle_radius=2), 
                                mp_drawing.DrawingSpec(color=(245,66,230), thickness=2, circle_radius=2) 
                                )               
        
        cv2.imshow('Mediapipe Feed', image)

        if cv2.waitKey(10) & 0xFF == ord('q'):
            break

    cap.release()
    cv2.destroyAllWindows()

    np.array(result).shape
    model = load_model('./model2.h5')
    a = np.array(result)
    b = model.predict(a)
    c = np.argmax(b, axis=1)
    print(c)
    val=[] 
    for i in range(len(c)):
        if c[i]==0: 
            val.append("정자세입니다.")
        elif c[i]==1:
            val.append("기구 당김이 부족합니다.")
        elif c[i]==2:           
            val.append("상체가 불안정하며, 손목이 꺾였습니다.")
        elif c[i]==3:
            val.append("상체가 불안정하며, 축 평행이 불량합니다.")
        elif c[i]==4:
            val.append("상체가 불안정하며, 기구 당김이 부족합니다")
        elif c[i]==5:
            val.append("손목이 꺾였으며, 축 평행이 불량합니다.")
        elif c[i]==6:
            val.append("속목이 꺾였이며, 기구 당김이 부족합니다.")
        elif c[i]==7:
            val.append("축 평행이 불량하며, 기구 당김이 부족합니다.")
        elif c[i]==8:
            val.append("속목이 꺾였으며, 기구 당김이 부족합니다.")
        elif c[i]==9:
            val.append("상체가 불안정하며, 기구 당김 부족합니다.")
        elif c[i]==10:
            val.append("상체 자세가 불안정하며, 기구 당김이 부족합니다.")
        elif c[i]==11:
            val.append("상체 자세가 불안정하며, 축 평행이 불량합니다.")
        elif c[i]==12:
            val.append("상체가 자세 불안정하며, 기구 당김이 부족합니다.")
    
    for j in range(len(val)): 
        print(val[j])




1/1 [==============================] - 1s 1s/step
[12  0  0 12  0]
상체가 자세 불안정하며, 기구 당김이 부족합니다.
정자세입니다.
정자세입니다.
상체가 자세 불안정하며, 기구 당김이 부족합니다.
정자세입니다.


In [37]:
for i in range(len(c)):
    print(c[i])
    

6
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
7
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
6
6
1
1
1
1
1
1
1
1
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13